### ISSUE TITLE
O Auth finalization

### ISSUE THREAD

**Issue by reeshavacharya** [reeshavacharya/Sahayog#1]
### ToDo 
- [x] re-structure the project
- [x] make logging in with google possible
- [x] a button on the navbar with user's profile picture which links to a simple progfile page
